// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Drive.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Drive::Drive(double turnAngle, double distance, double speed): Command() {
    m_turnAngle = turnAngle;
    m_distance = distance;
    m_speed = speed;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void Drive::Initialize() {
	printf("The Command Drive initialize\n");
}

// Called repeatedly when this Command is scheduled to run
void Drive::Execute() {
	printf("The Command Drive Execute\n");
}

// Make this return true when this Command no longer needs to run execute()
bool Drive::IsFinished() {
	printf("The Command Drive is Finished()\n");
    return false;
}

// Called once after isFinished returns true
void Drive::End() {
	printf("The Command Drive end()\n");
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Drive::Interrupted() {
	printf("The Command Drive getting interrupted\n");
}
