// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Drivetrain.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "../Commands/DriveWithJoysticks.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
const double Drivetrain::speed = 1.0;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Drivetrain::Drivetrain() : Subsystem("Drivetrain") {
	printf("The subsystem drivetrain constructor\n");

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    leftFrontMotor = RobotMap::drivetrainLeftFrontMotor;
    leftRearMotor = RobotMap::drivetrainLeftRearMotor;
    rightFrontMotor = RobotMap::drivetrainRightFrontMotor;
    rightRearMotor = RobotMap::drivetrainRightRearMotor;
    robotDrive41 = RobotMap::drivetrainRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void Drivetrain::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        SetDefaultCommand(new DriveWithJoysticks(0, 0, 0));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    printf("The drivetrain default command\n");
}


// Put methods for controlling this subsystem
// here. Call these from Commands.
void Drivetrain::takeJoystickInput(std::shared_ptr<Joystick> joystick) {
	printf("Take in the joystick input\n");
	Joystick *myJoystick = std::static_pointer_cast<Joystick>(joystick).get();
	robotDrive41->ArcadeDrive(myJoystick, Joystick::kYAxis, myJoystick, Joystick::kZAxis);
}

void Drivetrain::forward() {
	printf("The forward function for the drivetrain\n");
	leftFrontMotor->Set(0.5);
	leftRearMotor->Set(0.5);
	rightFrontMotor->Set(0.5);
	rightRearMotor->Set(0.5);
}

void Drivetrain::stop() {
	printf("The stop function for the drivetrain\n");
	robotDrive41->Drive(0, 0);
}
