// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::drivetrainLeftMotor;
std::shared_ptr<SpeedController> RobotMap::drivetrainRightMotor;
std::shared_ptr<RobotDrive> RobotMap::drivetrainTwoMotorDriver;
std::shared_ptr<SpeedController> RobotMap::armMotor;
std::shared_ptr<AnalogPotentiometer> RobotMap::armPotentiometer;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    printf("Running RobotMap init\n");

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    drivetrainLeftMotor.reset(new CANTalon(2));
    lw->AddActuator("Drivetrain", "LeftMotor", drivetrainLeftMotor);
    
    drivetrainRightMotor.reset(new Victor(1));
    lw->AddActuator("Drivetrain", "RightMotor", std::static_pointer_cast<Victor>(drivetrainRightMotor));
    
    drivetrainTwoMotorDriver.reset(new RobotDrive(drivetrainLeftMotor, drivetrainRightMotor));
    
    drivetrainTwoMotorDriver->SetSafetyEnabled(true);
        drivetrainTwoMotorDriver->SetExpiration(0.1);
        drivetrainTwoMotorDriver->SetSensitivity(0.5);
        drivetrainTwoMotorDriver->SetMaxOutput(1.0);
        drivetrainTwoMotorDriver->SetInvertedMotor(RobotDrive::kRearLeftMotor, true);
    armMotor.reset(new Talon(3));
    lw->AddActuator("Arm", "Motor", std::static_pointer_cast<Talon>(armMotor));
    
    armPotentiometer.reset(new AnalogPotentiometer(0, 1.0, 0.0));
    lw->AddSensor("Arm", "Potentiometer", armPotentiometer);
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
